### ISSUE TITLE
error during config check

### ISSUE THREAD

**Issue by tcurdt** [jethornton/mesact#1]
```
PROGRAM ERROR
A Program Error Occcured in checkconfig.py line 358
'bool' object is not subscriptable
```

Version 0.6.3

**Comment by tcurdt** [comment]
<img width="930" alt="Screenshot 2022-06-15 at 01 16 14" src="https://user-images.githubusercontent.com/13697/173704865-db7d16b1-3ff1-4bfb-b7ea-f854469e31e4.png">
<img width="910" alt="Screenshot 2022-06-15 at 01 16 27" src="https://user-images.githubusercontent.com/13697/173704872-6c28c6f1-e46e-4b83-a3b6-e6d010202080.png">
<img width="918" alt="Screenshot 2022-06-15 at 01 16 42" src="https://user-images.githubusercontent.com/13697/173704873-64d67bcd-9996-42cc-88ac-c30e78175f98.png">
<img width="934" alt="Screenshot 2022-06-15 at 01 17 02" src="https://user-images.githubusercontent.com/13697/173704875-4c3df3a2-12ce-49fc-aab2-ddaccfce9569.png">
<img width="925" alt="Screenshot 2022-06-15 at 01 17 11" src="https://user-images.githubusercontent.com/13697/173704880-51e43227-7f3c-42de-9619-207a715d4c06.png">
<img width="929" alt="Screenshot 2022-06-15 at 01 17 22" src="https://user-images.githubusercontent.com/13697/173704884-0c96f503-b59d-4f78-b30d-ea998e04ed4a.png">
<img width="923" alt="Screenshot 2022-06-15 at 01 17 33" src="https://user-images.githubusercontent.com/13697/173704887-e0c214dd-96f4-4589-9841-ebcf07fbae77.png">
<img width="928" alt="Screenshot 2022-06-15 at 01 17 43" src="https://user-images.githubusercontent.com/13697/173704888-f38eba2a-c3f0-41ea-8ba7-95ac037dd081.png">
<img width="931" alt="Screenshot 2022-06-15 at 01 17 52" src="https://user-images.githubusercontent.com/13697/173704890-f3cea250-607f-4d62-b7e6-e5b15dddf794.png">
<img width="919" alt="Screenshot 2022-06-15 at 01 18 05" src="https://user-images.githubusercontent.com/13697/173704892-527f9f36-9a89-4d7c-ae79-e5aa09f53015.png">
<img width="930" alt="Screenshot 2022-06-15 at 01 18 20" src="https://user-images.githubusercontent.com/13697/173704896-6566e958-cd37-4872-9e9d-fe934f0e3ec7.png">
<img width="929" alt="Screenshot 2022-06-15 at 01 18 27" src="https://user-images.githubusercontent.com/13697/173704897-d6be6f4f-96e4-4626-90ca-3bf5b52c4297.png">

**Comment by tcurdt** [comment]
seems to be related to the (missing) spindle settings

**Comment by jethornton** [comment]
This has been fixed
