### ISSUE TITLE
After the installation, it cannot be opened, please go to the detailed installation tutorial

### ISSUE THREAD

**Issue by chinaboy2277** [jethornton/mesact#100]
Mesact Version: 2.1.4 Build Date: 6/18/2024

  File "mesact", line 128, in <module>
    ex = MainWindow()
         ^^^^^^^^^^^^
  File "mesact", line 76, in __init__
    startup.setup(self)
  File "libmesact/startup.py", line 103, in setup
    version = line.split()[1]
              ~~~~~~~~~~~~^^^

IndexError
list index out of range

First download the deb and reinstall
to be sure you have the latest build date

Then please file an issue at
https://github.com/jethornton/mesact/issues

**Comment by chinaboy2277** [comment]
![截图_2024-06-28_17-01-40](https://github.com/jethornton/mesact/assets/16743392/715991c0-347b-4b25-8748-15a3746da3d3)

**Comment by jethornton** [comment]
What OS and what version of LinuxCNC is installed?

JT

**Comment by chinaboy2277** [comment]
debin 12 LINUXCNC - 2.9.2

**Comment by jethornton** [comment]
What does apt-cache policy 'linuxcnc-uspace' return in a terminal?

JT
