### ISSUE TITLE
Is there a detailed installation tutorial?

### ISSUE THREAD

**Issue by chinaboy2277** [jethornton/mesact#101]
![1719575848374](https://github.com/jethornton/mesact/assets/16743392/fbc808dd-1971-4916-97b9-bdf3147fd6d4)

**Comment by chinaboy2277** [comment]
![微信图片_20240628205344](https://github.com/jethornton/mesact/assets/16743392/0a43b3d1-3f6c-44b8-8072-49db470889a7)
![微信图片_20240628205421](https://github.com/jethornton/mesact/assets/16743392/5c130249-00db-4292-bb03-c6f8477c23b6)
![微信图片_20240628205456](https://github.com/jethornton/mesact/assets/16743392/0ea3bf6e-e76f-46e9-a05f-9d946d49148d)

**Comment by jethornton** [comment]
This was fixed this morning, get a fresh copy of the deb.

JT
