### ISSUE TITLE
Angular Scale Calculation Error

### ISSUE THREAD

**Issue by CodeThisPuppy** [jethornton/mesact#103]
I have 14T motor (200 pulse/rev) driving a 77T hub for 5.5:1 ratio, or 1100p/rev.   I should get a scale of 3.05555555p/deg.
Instead I get 2.78 when I input 5.5:1.  If I input 55:1 I get 30.55555 as expected.

![IMG_5990](https://github.com/jethornton/mesact/assets/174905054/87b4a78d-267e-4847-81fc-0e6f51894db9)
![IMG_5991](https://github.com/jethornton/mesact/assets/174905054/79914ccd-0b69-488c-b95e-b992c43f1dc9)

Am I doing something wrong?

**Comment by jethornton** [comment]
Thanks for the error report, this helps make the Mesa CT tool better.

JT
