### ISSUE TITLE
Servo Thread and NIC Test Calculate Error

### ISSUE THREAD

**Issue by morlan** [jethornton/mesact#103]
Error message when clicking "Calculate" under both Servo Thread Test and NIC Test.
![2023-04-07-170654_1920x1080_scrot](https://user-images.githubusercontent.com/4434648/230694510-72d6a73d-5c97-4d19-80a8-85d5102475be.png)

**Comment by morlan** [comment]
Manually entered 2000 MHz in CPU Speed and Servo Thread Test Calculate works now but not NIC Test Calculate.
![2023-04-07-171131_1920x1080_scrot](https://user-images.githubusercontent.com/4434648/230694631-f5906847-909a-4033-a41f-8bc0b17b2de2.png)

**Comment by jethornton** [comment]
Can you copy and paste the error messages? I can't read them...

JT

**Comment by jethornton** [comment]
Never mind I figured out how you got the first error and the second was fixed 2 weeks ago.

JT
