### ISSUE TITLE
Tab: Axes 

### ISSUE THREAD

**Issue by M-u-e-c-k-e** [jethornton/mesact#105]
**Version
Version = 1.2.4
Bord: 7i95

Tab: Axes 
I forgot to enter the value for Max Error (empty). 
Check is OK 
Build is OK 

Start of machine, error, value at MAX_ERROR in INI not available. 

The software forgot to query this ;-) 
After I entered a value, I could start the machine. 

Greetings Mücke

**Comment by jethornton** [comment]
Thanks for the report I'll fix that ASAP.

JT
