### ISSUE TITLE
Hello, still can not open, tried all methods, my Linuxcnc version is 2.9.3, the system is debian12, can not add a contact information, what is your email, my email is 435687044@qq.com, thank you very much for contacting you.

### ISSUE THREAD

**Issue by chinaboy2277** [jethornton/mesact#105]
![截图_2024-07-15_10-12-01](https://github.com/user-attachments/assets/344e0317-4806-4787-ac54-4cb20ae1646e)
![截图_2024-07-15_10-16-15](https://github.com/user-attachments/assets/447a6a52-0097-4bf1-a942-76d11468a6cb)
![截图_2024-07-15_10-17-06](https://github.com/user-attachments/assets/8b177426-efd8-469d-ac4f-b5006a5ae871)
![截图_2024-07-15_10-17-52](https://github.com/user-attachments/assets/9f909107-c798-4f9d-95ba-43c506a58b31)
Hello, still can not open, tried all methods, my Linuxcnc version is 2.9.3, the system is debian12, can not add a contact information, what is your email, my email is 435687044@qq.com, thank you very much for contacting you.

**Comment by jethornton** [comment]
I will need the output from apt-cache policy linuxcnc-uspace to determine the error. I can not reproduce the error.

**Comment by chinaboy2277** [comment]
Hello, can you tell me how to operate, and I'll show you what the problem is?

**Comment by chinaboy2277** [comment]
![截图_2024-07-15_19-36-06](https://github.com/user-attachments/assets/1cdec614-9b6f-49aa-84a1-b6718d155e37)

**Comment by chinaboy2277** [comment]
china@debian:~$ sudo apt-cache search mesact
mesact - Mesa Configuration Tools for LinuxCNC
china@debian:~$ sudo apt-cache show mesact
Package: mesact
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 3383
Maintainer: John Thornton <dev@gnipsel.com>
Architecture: amd64
Version: 2.1.4
Depends: python3 (>= 3.6), python3-pyqt5 (>= 5.15.0), python3-packaging, python3-requests, zip, python3-distro
Suggests: linuxcnc-uspace, mesaflash
Description: Mesa Configuration Tools for LinuxCNC
 This software can create configuration files used by LinuxCNC to
 control 5i25/6i25, 7i76e, 7i80, 7i92, 7i95, 7i95T, 7i96, 7i96S, 7i97 and 7i98
 Mesa Electronics motion control boards, smart serial boards and daughter cards.
Description-md5: 0e5aa445229743013db1bebabb617671

**Comment by chinaboy2277** [comment]
![截图_2024-07-15_19-52-10](https://github.com/user-attachments/assets/5467675b-a9be-4e1d-a0a6-f0d6694e2a9e)

**Comment by jethornton** [comment]
Run the command apt-cache policy linuxcnc-uspace in a terminal and post the output from that command here. Please no screen shots of the terminal just copy and paste the output.

**Comment by chinaboy2277** [comment]
china@debian:~$ apt-cache policy linuxcnc-uspace
linuxcnc-uspace:
  已安装：2.9.0~pre1+git20230208.f1270d6ed7-1
  候选： 1:2.9.3
  版本列表：
     1:2.9.3 500
        500 https://www.linuxcnc.org bookworm/2.9-uspace amd64 Packages
     1:2.9.2 500
        500 https://www.linuxcnc.org bookworm/2.9-uspace amd64 Packages
     1:2.9.1 500
        500 https://www.linuxcnc.org bookworm/2.9-uspace amd64 Packages
 *** 2.9.0~pre1+git20230208.f1270d6ed7-1 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by chinaboy2277** [comment]
***@***.***：$ apt-cache policy linuxcnc-uspace
linuxcnc-uspace：
已安装：2.9.0pre1+git20230208.f1270d6ed7-1
候选： 1：2.9.3
版本列表：
1：2.9.3 500
500 https://www.linuxcnc.org&nbsp;bookworm/2.9-uspace amd64 软件包
1：2.9.2 500
500 https://www.linuxcnc.org&nbsp;bookworm/2.9-uspace amd64 软件包
1：2.9.1 500
500 https://www.linuxcnc.orgbookworm/2.9-uspace amd64 软件包
*** 2.9.0~pre1+git20230208.f1270d6ed7-1 500
500 http://deb.debian.org/debian&nbsp;bookworm/main amd64 软件包
100 /var/lib/dpkg/status




小磊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jethornton/mesact"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月16日(星期二) 凌晨5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jethornton/mesact] Hello, still can not open, tried all methods, my Linuxcnc version is 2.9.3, the system is debian12, can not add a contact information, what is your email, my email is ***@***.***, thank you very much for contacting you. (Issue #105)





 
Run the command apt-cache policy linuxcnc-uspace in a terminal and post the output from that command here. Please no screen shots of the terminal just copy and paste the output.

**Comment by jethornton** [comment]
Thank you, I've made a change that should stop the error. If not open this issue back up.

JT

**Comment by chinaboy2277** [comment]
Hello, when will this problem be fixed?

**Comment by jethornton** [comment]
2 hours ago

**Comment by chinaboy2277** [comment]
Hello, thank you very much, the software is now running, I checked and found that there is no mesa 7i92 and DB25 expansion card configuration?? Hope you can add, DB25 expansion card is very cheap, suitable for entry-level beginners to use, there is no Chinese support, China has a lot of friends want to learn linuxcnc, hope to improve, thank you again.

**Comment by chinaboy2277** [comment]
![1721183364694](https://github.com/user-attachments/assets/8de936c3-5b0c-4b4e-8e34-918ea678e89d)
![bob_wiring_diagram_new](https://github.com/user-attachments/assets/4a50d858-5aab-4eac-a88a-c1b4523dc424)
