### ISSUE TITLE
Pin #ing Issue in HAL files

### ISSUE THREAD

**Issue by sokrdz** [jethornton/mesact#115]
Hi,

Starting off, really appreciate the tool, it's a clean version of pnconf and has helped me a lot so far so thank you for developing it.

My board configuration: 7i96s + 7i77 (via DB25)
firmware:7i96s_7i77d.bin
LinuxCNC 2.93
Mesaflash 3.4.9
Python 3.11.2

Issue only seems to be with respect to 7i77 pins although haven't confirmed with host board yet.

Just starting out and creating a configuration with only 1 axis (X) and it seems MesaCT generates the following hal file that causes LinuxCNC to error upon start up.

Debug message:
'./main.hal:77: Pin 'hm2_7i96s.0.7i77.0**.4.**analogout0' does not exist'

Reading Mesa documentation, pin out should be:

"(float in) .7i77.0.1.analogoutN: (N = 0 to 5) This controls the analog output of the 7I77." 
Updating .hal file line from 4 to 1 fixes issue.

Pin outs in io.hal file are also not starting at 0 also.

'# Inputs
net joint-0-home joint.0.home-sw-in <= hm2_7i96s.0.7i77.0.3.input-01'
Updating .hal file from 3 to 0 fixes error.

Is there something that is missing in my set up configuration or is this a bug?

Thanks,
Michael

**Comment by jethornton** [comment]
Looks like a bug, I'll look into fixing it.

JT

**Comment by jethornton** [comment]
Can you attach your ini file?

JT

**Comment by sokrdz** [comment]
Attached is the .ini and edited .hal


[test_x_only_7i77_ini.txt](https://github.com/user-attachments/files/16900282/test_x_only_7i77_ini.txt)

[main_hal.txt](https://github.com/user-attachments/files/16900285/main_hal.txt)

**Comment by jethornton** [comment]
This might take a while to sort out, I'm thinking I need to totally rewrite the hal section.

JT

**Comment by jethornton** [comment]
Got the port number for the daughter card sorted out. On to the next bug...

JT

**Comment by jethornton** [comment]
Fixed the analog port numbers for 7i96s. On to the next bug...

JT

**Comment by jethornton** [comment]
Everything should be fixed if not just open a new issue.

JT

**Comment by sokrdz** [comment]
Thank you!
