### ISSUE TITLE
Axle with two joint ?error?

### ISSUE THREAD

**Issue by M-u-e-c-k-e** [jethornton/mesact#115]
Version: 1.2.4

I want to create an axis (Z) with two motors (Joint0 & Joint 1). 
I get the error: 
[Quote]
There are Errors in the Config
Do you want to save the ini file
and come back later to fix the Errors?

Axes Tab:
	Multiple Joint Axis Z joint0 & joint1 must be negative for at least one Joint.
Build Failed
[/Quote]

What is meant by this? 
I don't understand what needs to be changed.

**Comment by jethornton** [comment]
The Home Sequence must be negative for a multiple joint axis.
