### ISSUE TITLE
Angular velocities

### ISSUE THREAD

**Issue by persei802** [jethornton/mesact#116]
**Please use English for Bug Report**

**Version and Build Date**
Version = 1.2.3
Build Date =02/04/2023

**Describe the bug**
The check config tool reports:
Settings Tab:
	Default Angular Jog Velocity must be greater than zero
	Maximum Angular Jog Velocity must be greater than zero
However, those fields on the Settings tab are greyed out and it will not build the config file.
My axis configuration is XYZYA for joints 0 to 4, respectively.
All fields in the Axes tab are filled in.

**To Reproduce**
1. Go to 'Machine tab'
2. Click on 'Board'
3. Scroll down to '7i96'

**Expected behavior**
I expect the angular velocity fields to be enabled so I can fill them in and generate a configuration file.
**Config File**
Attach the ini file that has the bug in it.
There isn't one.
**Operating System**
 OS =  Debian 11

**Additional context**

**Comment by jethornton** [comment]
Thanks for the Issue Report but I can not reproduce that with the current Version 1.2.4 Build Date 08/14/23.

I selected 7i96 then on any joint select an angular axis this enables all the Angular Velocity spin boxes.

Always do Check for Updates from the Help menu first when you encounter an error or bug.

JT

**Comment by persei802** [comment]
Thanks for the quick response. I updated to 1.2.4 and have to go through
the whole process again but I noticed it's not fetching the latest cache of
firmware files. The one I need is 7i96_pktdv2.bit but it's not listed in
the fetched firmwares. This means I can't use your tool to flash the board.
I find using mesaflash very cumbersome.
Jim

**Comment by persei802** [comment]
BTW, how did you build this version 2 months in the future? :_)

**Comment by jethornton** [comment]
Keyboard has a mind of it's own... the 8 is above the 5...

That firmware was only added very recently and I was not aware that any firmware has been added to the 7i96 which is no longer in production. The firmware repository has been updated to include the latest firmware from Mesa.

JT

**Comment by jethornton** [comment]
Attach a copy of the ini file.

JT

**Comment by persei802** [comment]
I tried but got "We don't support that file type" 
Try this.
[mesa.ini.tar.gz](https://github.com/jethornton/mesact/files/11900261/mesa.ini.tar.gz)

**Comment by jethornton** [comment]
I'll have to try with Debian 11, all the angular boxes are enabled when I open your configuration in Debian 12. However I do see that the group box needs to be a bit wider...

![Screenshot at 2023-06-28 17-28-59](https://github.com/jethornton/mesact/assets/5452476/2752be8e-5773-46a6-917f-c67595b7ad61)

**Comment by jethornton** [comment]
![Screenshot at 2023-06-29 07-54-54](https://github.com/jethornton/mesact/assets/5452476/5ffc9d34-1486-46fe-a1d9-694ecad81930)

![Screenshot at 2023-06-29 07-55-20](https://github.com/jethornton/mesact/assets/5452476/15346a43-5b5c-4579-bebf-b624e576e7f3)

I'm unable to reproduce this in Debian 11.

JT

**Comment by persei802** [comment]
Not to worry. So long as it builds the ini file, even if there are errors in it. I need to make other edits to it anyway. BTW, I was looking through your code and I must say, that is some nice work. I may get some good ideas from it with my own work on QtDragon. You may consider this issue closed.

**Comment by jethornton** [comment]
Thanks, take a look at mesact2 if your interested in the code base. I've made a lot of improvements there and that is my current project to finish it up and replace mesact with it.

JT
