### ISSUE TITLE
7i95

### ISSUE THREAD

**Issue by M-u-e-c-k-e** [jethornton/mesact#3]
Hello all, 

the 7i95 tool seems to have been merged with others? 

Is the Mesact 2 or the Mesact the current one for the 7i95 card? 
There is no description online for the Mesact 2 yet :-( 

Gruß Mücke

**Comment by jethornton** [comment]
MesaCT2 is under heavy development at the moment and is not ready to create a working configuration for any card. You're welcome to look around and make suggestions about the interface part.

JT

**Comment by M-u-e-c-k-e** [comment]
Hello jethornton,

Thank you for the offer to provide feedback and ideas (of which I have many).

Is the MesaCT tool being replaced?
If so, is it still worth reporting bugs and issues in MesaCT?

Best regards,
Mücke

**Comment by jethornton** [comment]
For the time being yes report bugs for MesaCT. Once MesaCT2 is operational it will replace MesaCT.

JT

**Comment by jethornton** [comment]
If you wish to help test MesaCT2 I am currently testing updating the INI axis and joints. Instructions are shown when loading the tool.

JT

**Comment by M-u-e-c-k-e** [comment]
I am new myself and don't know my way around. 
I like to test when a working machine comes out. 
I am happy to report bugs then. 

For me, who doesn't understand HAL and INI, such software is very important and good!

**Comment by M-u-e-c-k-e** [comment]
I am more of a GUI user tester ;-)
