### ISSUE TITLE
Bug or Feature ;)

### ISSUE THREAD

**Issue by steirerman** [jethornton/mesact#3]
I installed the file MESACT 0.6.3 and tried to load my configuration, which ends with an error message.
And I don't see anywhere a support for the 6i25+7i74 >7i66-8+7i64

PROGRAM ERROR
A Program Error Occurred in configparser.py line 1079
File contains no section headers.
file: '/home/chiron/linuxcnc/configs/chironFZ16/chiron.ini', line: 4
'\ufeff\n'

chiron@ChironFz16:~$ mesact
File configparser.py line 1079, in _read
["configparser.MissingSectionHeaderError: File contains no section headers.\nfile: '/home/chiron/linuxcnc/configs/chironFZ16/chiron.ini', line: 4\n'\\ufeff\\n'\n"]

My Config:

[EMC]
# The version string for this INI file.
VERSION = 1.1

# Name of machine, for use with display, etc.
MACHINE =               ChironFZ16

# Debug level, 0 means no messages. See src/emc/nml_int/emcglb.h for others
#Debug level, 0 means no messages. See src/emc/nml_intf/debugflags.h for others
#DEBUG = 0x00000002 # configuration
#DEBUG = 0x7FFFDEFF # no interp,oword
#DEBUG = 0x00008000 # py only
#DEBUG = 0x0000E000 # py + remap + Oword
#DEBUG = 0x0000C002 # py + remap + config
#DEBUG = 0x0000C100 # py + remap + Interpreter
#DEBUG = 0x0000C140 # py + remap + Interpreter + NML msgs
#DEBUG = 0x0000C040 # py + remap + NML
#DEBUG = 0x0003E100 # py + remap + Interpreter + oword + signals + namedparams
#DEBUG = 0x10000000 # EMC_DEBUG_USER1 - trace statements
#DEBUG = 0x20000000 # EMC_DEBUG_USER2 - trap into Python debugger
#DEBUG = 0x10008000 # USER1, PYTHON
#DEBUG = 0x30008000 # USER1,USER2, PYTHON # USER2 will cause involute to
DEBUG = 0x7FFFFFFF # All debug messages

[DISPLAY]

EDITOR = gedit
DISPLAY = gmoccapy
EMBED_TAB_NAME = Chiron
EMBED_TAB_LOCATION = box_right
EMBED_TAB_COMMAND = gladevcp -x {XID} -H Chiron.hal Chiron.glade
CYCLE_TIME =    100
#Probe_Screen
#EMBED_TAB_NAME=Siggis Probe Screen
#EMBED_TAB_LOCATION = ntb_user_tabs
# EMBED_TAB_COMMAND = gladevcp -x {XID} -H probe_screen.hal -u python/probe_screen.py probe_icons/probe_screen.glade
#EMBED_TAB_COMMAND=gladevcp -c siggi -x {XID} -u nc_subroutines/psng/python nc_subroutines/psng/psng_mod.glade
#EMBED_TAB_COMMAND=gladevcp -x {XID} nc_subroutines/psng/python -H nc_subroutines/psng/psng.hal nc_subroutines/psng/psng_mod.glade
#EMBED_TAB_COMMAND=gladevcp -c probe -x {XID} -u nc_subroutines/psng/python -H nc_subroutines/psng/psng.hal nc_subroutines/psng/psng_mod.glade

# Highest value that will be allowed for feed override, 1.0 = 100%
MAX_FEED_OVERRIDE =     1.5
MIN_FEED_OVERRIDE =     0.5
MAX_SPINDLE_OVERRIDE =  1.5
MIN_SPINDLE_OVERRIDE =   .5
DEFAULT_SPINDLE_SPEED = 4500
MAX_RAPID_OVERRIDE = 2.0
# Max and default jog speeds in units per second
MAX_LINEAR_VELOCITY =     16
DEFAULT_LINEAR_VELOCITY = 5
MAX_ANGULAR_VELOCITY =    234

# Path to help file
HELP_FILE =             tklinucnc.txt

# Initial display setting for position, RELATIVE or MACHINE
POSITION_OFFSET =       RELATIVE

# Initial display setting for position, COMMANDED or ACTUAL
POSITION_FEEDBACK =     ACTUAL

# Prefix to be used
PROGRAM_PREFIX = /home/chiron/linuxcnc/nc_files

# Introductory graphic
INTRO_GRAPHIC =         linuxcnc.gif
INTRO_TIME =            2
GEOMETRY =              XYZ
INCREMENTS = 1 mm, 0.1 mm, 0.01mm, 0.001mm

# for details see nc_files/subroutines/marco_instructions.txt

[APPLICATIONS]
#APP = monitor-xhc-hb04

[FILTER]
PROGRAM_EXTENSION = .png,.gif,.jpg Grayscale Depth Image
PROGRAM_EXTENSION = .py Python Script
png = image-to-gcode
gif = image-to-gcode
jpg = image-to-gcode
py = python

[RS274NGC]
SUBROUTINE_PATH = ./chironFZ16:./macros:./nc_subroutines/psng:./nc_subroutines/psng/macros
USER_M_PATH = ./nc_subroutines/remap
PARAMETER_FILE  = hm2-servo.var
RS274NGC_STARTUP_CODE = G17 G21 G40 G43H0 G54 G64P0.005 G80 G90 G94 G97 M5 M9

#New format for feature :
INI_VARS = 1
HAL_PIN_VARS = 1
RETAIN_G43 = 0

# this is important with remap - read nc_subroutines/reset_state.ngc
ON_ABORT_COMMAND=o<backup_restore> call

#REMAP=M6  modalgroup=10           python=tool_probe_m6
#REMAP=M6  modalgroup=10           python=tool_probe_m6

# optional features - a bit mask to selectively turn on experimental/dubious features
# see 
# RETAIN_G43           0x00000001
# OWORD_N_ARGS         0x00000002
# INI_VARS             0x00000004
# HAL_PIN_VARS         0x00000008
# NO_DOWNCASE_OWORD    0x00000010
# turn on all optional features

# turn on optional features in this case just INI reading 
FEATURES=12

#ON_ABORT_COMMAND=O <on_abort> call 

# parameters exposed by change_prolog/evaluated by change_epilog:
#    #<tool_in_spindle>
#    #<selected_tool>
#    #<current_pocket>
#    #<selected_pocket>
#REMAP=M6  modalgroup=6 prolog=change_prolog ngc=change epilog=change_epilog
# accessible in interp as #<_[section]name>
# start of tool length touchoff probe
# Motion control section ------------------------------------------------------
;REMAP=M6 modalgroup=6 ngc=toolprobe
[EMCMOT]
EMCMOT =              motmod
COMM_TIMEOUT =          1.0
BASE_PERIOD  =          100000
SERVO_PERIOD =          1000000

[TASK]

# Name of task controller program, e.g., milltask
TASK =                  milltask

# Cycle time, in seconds, that task controller will sleep between polls
CYCLE_TIME = 0.010

[HAL]

POSTGUI_HALFILE = gmoccapy_postgui.hal
HALUI = halui

HALFILE = hm2-servo.hal
HALFILE = ios.hal
HALFILE = loadrt.hal
HALFILE = Maschine.hal
HALFILE = Spindel.hal
HALFILE = Bedienfeld.hal
HALFILE = Werkstueckwechsler.hal
HALFILE = Werkzeugwechsler.hal
HALFILE = Meldung.hal
HALFILE = 6i25.hal
HALFILE = xhc-whb4.hal
#HALFILE = probe_screenV2.hal

[HALUI]

#halui.mdi-command-00
MDI_COMMAND = G10 L20 P1 X 0     ( X-Ursprung setzen )
                                             
#halui.mdi-command-01
MDI_COMMAND = G10 L20 P1 Y 0     ( Y-Ursprung setzen )
                                             
#halui.mdi-command-02
MDI_COMMAND = G10 L20 P1 Z 0     ( Z-Ursprung setzen )

# halui.mdi-command-05
# MDI_COMMAND = o<antasten> call   ( Programm uebertragen )
#MDI_COMMAND=(debug,00)
#MDI_COMMAND=(debug,macro1)
#MDI_COMMAND=(debug,macro2)
#MDI_COMMAND=(debug,macro3)
#MDI_COMMAND=(debug,macro4)
#MDI_COMMAND=G1 G53 X0 Y0 Z0 F4000
#MDI_COMMAND=(debug,macro6)
#MDI_COMMAND=G1 X0 Y0 Z0 F4000
#MDI_COMMAND=(debug,macro8)
#MDI_COMMAND=(debug,macro9)
#MDI_COMMAND=(debug,macro10)
#MDI_COMMAND=(debug,macro11)
#MDI_COMMAND=(debug,macro12)
#MDI_COMMAND=(debug,macro13)
#MDI_COMMAND=(debug,macro14)
#MDI_COMMAND=(debug,macro15)
#MDI_COMMAND=(debug,macro16)
#MDI_COMMAND=G1 G53 Z0 F4000
#MDI_COMMAND=(debug,macro17)
#MDI_COMMAND=(debug,macro18)
#MDI_COMMAND=(debug,macro19)

[TRAJ]

AXES =                  3
# COORDINATES =         X Y Z R P W
COORDINATES =           X Y Z
HOME =                  0 0 0 0
LINEAR_UNITS =          mm
ANGULAR_UNITS =         degree
DEFAULT_LINEAR_VELOCITY =      50.0
MAX_LINEAR_VELOCITY =          250.0
DEFAULT_ACCELERATION =  400.0
MAX_LINEAR_ACCELERATION =      1200.0
#NO_FORCE_HOMING =       1

[EMCIO]
EMCIO = 		iov2
TOOL_CHANGE_WITH_SPINDLE_ON = 0

# tool table file
TOOL_TABLE = tool.tbl
#TOOL_TABLE = *******.tbl
TOOL_CHANGE_QUILL_UP = 1
TOOL_CHANGE_POSITION = 23 0 0
# tool change
#******************************************
[TOOL_SETTER]
#******************************************
# Absolute XYZ G53 machine coordinates for start probing
## off course you need to keep TS_HEIGHT + TS_MAX_TOOL_LGT + CLEARANCE_Z result inside your machine limit range
TS_POS_X = 18.17
TS_POS_Y = 38.4
TS_POS_Z = -413,5916
#TS_POS_Z is for now only used in stglue remap    :  TODO update code

# ts_height is used only with "real toolsetter" or "touchplate" at fixed location
TS_HEIGHT = 11.46

# Maximum probing search distance you need to know the max length tool you can use on your machine CLEARANCE_Z is added automatically
TS_MAX_TOOL_LGT = 60

# if your tool setter or plate allow to use XY you can configure more than 0
PROBE_MAX_XY = 10

# REPLACE THE MACHINE XY LIMIT MAX USING JOINT VALUE FOR ALLOW GOTO TOOLSENSOR OUTSIDE OF AXIS LIMIT using M171 Pxx user-defined Mcode
CHANGE_X_LIMIT_MCODE = 170
CHANGE_Y_LIMIT_MCODE = 171

# Travel velocity for probe rapid move
VEL_FOR_TRAVEL = 1200

# Fast first probe tool velocity : spring mounted touchplate/toolsetter allow faster speed
VEL_FOR_SEARCH = 150

# Slow final probe velocity
VEL_FOR_PROBE = 10

# clearence is used for up down on the side of the toolseteer for tool diameter measurement
# this value need to be less than the TS_HEIGHT for calculating the position correctly !!)
CLEARANCE_Z = 5
CLEARANCE_XY = 5

# Latched distance for probing use value like 1mm (more than the spring movement if you do not use reverse probing)
# this value need to be less than the TS_HEIGHT for calculating the position correctly !!)
LATCH = 1

# You can use latch_reverse_probing with G38.5 with value like 2mm (more than the distance needed for release the contact)
# or 0 if you want to inhibit G38.5)
PROBE_MAX_LATCH = 2

# Diameter of toolsetter pad
DIAMETER_EXT = 10
DIAMETER_HOLE = 14

# offset to add from touching toolsetter pad to signal triggering
DIAM_OFFSET = 0

# The speed of the reverse rotation of the spindle when measuring the tool diameter
TOOL_ROT_SPEED = 0
#******************************************

#******************************************
[TOOL_CHANGE]
#******************************************
# Allow user to chose original popup style dialog box for toolchange or new method using pause and Gcode message
################TODO
POPUP_STYLE = 0

# After tool change choose if you wan't to go back to last position or return to "Quil up" or "z travel position" and finally to XY change position
GO_BACK_LAST_POSITION = 1

# Position absolue in machine coordinate for all XY rapid move G53 machine cooordinates
Z_TRAVEL_POSITION = 0

# Abs coordinates for tool change point G53 machine cooordinates
X = 0
Y = 0
Z = 0
#******************************************

#******************************************
[TOUCH_DEVICE]
#******************************************
# Allow user to chose original popup style dialog box for toolchange or new method using pause and Gcode message
POPUP_STYLE = 0

# Allow user to define the toolnumber used for securing the probe (need to be in the tooltable with precise diameter)
# If you do not have a 3D Probe you need to set PROBE_NUMBER = 0
PROBE_NUMBER = 999

# Used here for manage tool setter input
PROBE_ON_MCODE = 165
PROBE_OFF_MCODE = 166

# Only used here for reactivate tool setter input if they are deactivated by other way like PSNG or user
TOOL_SETTER_ON_MCODE = 167
TOOL_SETTER_OFF_MCODE = 168

# plate thickness used as movable probe device for Z (full thickness if you have touchplate with XY corner)
PLATE_Z_FULL_THICKNESS = 7
PLATE_Z_THICKNESS = 4
PLATE_XY_THICKNESS = 8

# TABLE CLEARENCE USED FOR PREVENT Z probe move zxceed limit also used for dynamicZ
TABLE_CLEARENCE = 0.05

# provide file name and method for compensation gridd
METHOD = cubic
FILE_NAME = probe-compensation-gridd-results.txt

# the Python plugins serves interpreter and task
[PYTHON]
PATH_PREPEND = python
TOPLEVEL = python/toplevel.py
LOG_LEVEL = 8

[KINS]
KINEMATICS = trivkins coordinates=xyz
JOINTS = 3

[AXIS_X]
MIN_LIMIT = -490
MAX_LIMIT = 45
MAX_VELOCITY = 166.6666667
MAX_ACCELERATION = 350.0

[JOINT_0]

TYPE =                  LINEAR
MAX_VELOCITY =          166.6666667
MAX_ACCELERATION =      1000.0
# STEPGEN_MAXACCEL =      4000
BACKLASH =              0.0002
FERROR =                10
MIN_FERROR =            0.2

INPUT_SCALE =           823
#ENCODER_SCALE=          2048
OUTPUT_SCALE =          166.6667
OUTPUT_OFFSET =         0.0
MAX_OUTPUT =            166.6667
MIN_LIMIT =             -490
MAX_LIMIT =             45
HOME =                  0.000
HOME_OFFSET =           -0
HOME_SEARCH_VEL =       -30
HOME_LATCH_VEL =        -1
HOME_SEQUENCE =          1

HOME_USE_INDEX =        YES
HOME_IGNORE_LIMITS =    NO

# PID tuning params
DEADBAND =              0.000049
P =                     100
I =                     0
D =                     0
FF0 =                   0
FF1 =                   1
FF2 =                   0
BIAS =                  0

[AXIS_Y]
MIN_LIMIT = -173
MAX_LIMIT = 87.5
MAX_VELOCITY = 166.6666667
MAX_ACCELERATION = 1000.0

[JOINT_1]

TYPE =                  LINEAR
MAX_VELOCITY =          166.6666667
MAX_ACCELERATION =      1000.0
# STEPGEN_MAXACCEL =      4000
BACKLASH =              0.00025
FERROR =                5.0
MIN_FERROR =            0.1

INPUT_SCALE =           823

OUTPUT_SCALE =          166.6667
OUTPUT_OFFSET =         0.0
MAX_OUTPUT =            166.6667

MIN_LIMIT =             -173
MAX_LIMIT =             87.5
HOME =                  0.000
HOME_OFFSET =           -0
HOME_SEARCH_VEL =       -30
HOME_LATCH_VEL =        -1
HOME_SEQUENCE =          1

HOME_USE_INDEX =        YES
HOME_IGNORE_LIMITS =    NO

# PID tuning params
DEADBAND =              0.000049
P =                     100
I =                     0
D =                     0
FF0 =                   0
FF1 =                   1
FF2 =                   0
BIAS =                  0

[AXIS_Z]
MIN_LIMIT = -424
MAX_LIMIT = 2
MAX_VELOCITY = 250.0
MAX_ACCELERATION = 1000.0

[JOINT_2]

TYPE =                  LINEAR
MAX_VELOCITY =          250.0
MAX_ACCELERATION =      1000.0
# STEPGEN_MAXACCEL =      4000
BACKLASH =              0.00025
FERROR =                5.0
MIN_FERROR =            0.1

INPUT_SCALE =           816.5

OUTPUT_SCALE =          166.6667
OUTPUT_OFFSET =         0.0
MAX_OUTPUT =            166.6667

MIN_LIMIT =             -424
MAX_LIMIT =             2
HOME =                  0
HOME_OFFSET =           -80
HOME_SEARCH_VEL =       -30
HOME_LATCH_VEL =        -1
HOME_SEQUENCE =          0

HOME_USE_INDEX =        YES
HOME_IGNORE_LIMITS =    NO

# PID tuning params
DEADBAND =              0.000049
P =                     100
I =                     0
D =                     0
FF0 =                   0
FF1 =                   1
FF2 =                   0
BIAS =                  0

[HOSTMOT2]
DRIVER=hm2_pci
BOARD=5i20
#CONFIG="num_encoders=2 num_stepgens=5 sserial_port_0=002000,firmware=hm2/5i20/svst6_6_7i48.bit num_encoders=6 num_pwmgens=6 num_stepgens=0num_leds=0,firmware=hm2/5i20/SVST2_4_7I47.BIT num_encoders=0 num_pwmgens=0 num_stepgens=0num_leds=0" sserial_port_1=0000000sserial_port_1=000xxx

CONFIG="num_encoders=0 num_stepgens=0 sserial_port_1=021xxx,firmware=hm2/5i20/svst6_6_7i48.bit num_encoders=6 num_pwmgens=6 num_stepgens=0num_leds=0,firmware=hm2/5i20/svst6_6_7i48.bit num_encoders=0 num_pwmgens=0 num_stepgens=0num_leds=0"
#CONFIG="num_encoders=0 num_stepgens=0 sserial_port_0=002xxx,firmware=hm2/5i20/svst6_6_7i48.bit num_encoders=6 num_pwmgens=6 num_stepgens=0num_leds=0,firmware=hm2/5i20/svst6_6_7i48.bit num_encoders=0 num_pwmgens=0 num_stepgens=0num_leds=0"
[MACROS]
MACRO = i_am_lost
MACRO = halo_world
MACRO = feierabend
MACRO = increment xinc yinc
MACRO = go_to_position X-pos Y-pos Z-pos
MACRO = toolprobe

[SPINDEL]

MAX_DREHZAHL =          4500                     
PP_U =                  1024                                  
UEBERSTEUERUNG =        2.0                    
DEADBAND =              0.000015              
P =                    100                    
I =                     0                     
D =                     0                     
FF0 =                   0                     
FF1 =                   1                     
FF2 =                   0                     
BIAS =                  0                     
MAX_OUTPUT =            100    

#[TOOLSENSOR]
# Control probe rapid speed
#RAPID_SPEED = 600
#X = -415.914
#Y = -146.579
#Z = -285
#MAXPROBE =  -20

[FILTER]
PROGRAM_EXTENSION = .png,.gif,.jpg Grayscale Depth Image
PROGRAM_EXTENSION = .py Python Script
png = image-to-gcode
gif = image-to-gcode
jpg = image-to-gcode
py = python

**Comment by jethornton** [comment]
The Mesa Configuration Tool will only open an ini file created by the tool.
