### ISSUE TITLE
Enhancement: Foam cutting and Filter/filetype extensions

### ISSUE THREAD

**Issue by boozeman** [jethornton/mesact#30]
![image](https://user-images.githubusercontent.com/40159019/194358191-99835636-3918-4fe8-8857-601e2438f709.png)
Is it possible to Add Foam Cutter option here with dropdown or manual list for geometry option, Default is XY;UV but I have seen also XY;ZA and XY;UZ combinations.

[Display] section on ini:
```
Geometry = XY;UV
FOAM = 1
```
Another useful feature is the [Filter] section with some extensions, etc. 

on ini:

```
[FILTER]
PROGRAM_EXTENSION = .png,.gif,.jpg Greyscale Depth Image
PROGRAM_EXTENSION = .py Python Script
PROGRAM_EXTENSION = .nc,.tap,ncg G-Code File
png = image-to-gcode
gif = image-to-gcode
jpg = image-to-gcode
py = python
```

This is a just nitpicking and it is not too hard to add these on the ini by hand, but Mesact will erase them if you do some changes to the configuration and sometimes I forget to add them back manually. 

Cheers

**Comment by jethornton** [comment]
I'll work on adding foam and the good news is I'm totally changing the ini update to not write over any valid section(s) and key/value pairs or any comments that start with # or ; in the ini3 branch.

Multiple keys in a section is still a problem for me... thinking about that... adding one filter could be done easy.

JT
