### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by M-u-e-c-k-e** [jethornton/mesact#39]
Hello, 

What am I doing wrong? 

I have deleted the old version. 
_cnc@debian:~$ sudo apt-get remove mesact_

I have downloaded and unpacked the new version (ZIP). 

Now I wanted to call up the version via the terminal. 
_cnc@debian:~ $ cd /home/cnc/Schreibtisch/mesact-master/mesact/src/
cnc@debian:~ /Schreibtisch/mesact-master/mesact/src$ ./mesact_

I get the message, 
Quote: _"PyQt5 5.15 or newer is required.
            Your PyQt5 is 5.11.3
            Try updating python3-pyqt5"_

I wanted to update PyQt: 
_cnc@debian:~ $ cd /home/cnc/Schreibtisch/mesact-master/mesact/src/
cnc@debian:~ /Schreibtisch/mesact-master/mesact/src$ sudo apt install python3-pyqt5
[sudo] Passwort für cnc: 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
python3-pyqt5 ist schon die neueste Version (5.11.3+dfsg-1+b3).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 158 nicht aktualisiert.
cnc@debian:~/Schreibtisch/mesact-master/mesact/src$_ 

and
_cnc@debian:~ /Schreibtisch/mesact-master/mesact/src$ sudo apt install python3-packaging
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
python3-packaging ist schon die neueste Version (19.0-1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 158 nicht aktualisiert.
cnc@debian:~ /Schreibtisch/mesact-master/mesact/src$_ 

What am I doing wrong?

**Comment by jethornton** [comment]
python-pyqt5 5.15 is in Debian 11 (Bullseye) I'm not sure how you can back port python-pyqt5 from Debian 11 to Debian 10.

JT

**Comment by M-u-e-c-k-e** [comment]
Oha then I have to update my "Debian GNU/Linux 10 (buster)" to Debian 11 (Bullseye). 

I'll have to see how that can be done. 
Setting up the computer again, setting up the network card etc. is really a lot of work. 

Gruß Mücke 

[Edit]
I've found something that sounds good, I'm going to test it now and hope that everything goes well. 
https://www.cyberciti.biz/faq/update-upgrade-debian-10-to-debian-11-bullseye/

**Comment by M-u-e-c-k-e** [comment]
The update worked, I now have 
Debian GNU/Linux 11 (Bullseye)
but my LinuxCNC is no longer on the computer. 

But I can open mesact via the terminal, will there also be an icon for the desktop?

**Comment by jethornton** [comment]
When mesact is installed and LinuxCNC is not installed the menu is located in Applications > Accessories.

JT

**Comment by M-u-e-c-k-e** [comment]
Okay, I haven't installed it yet. 
Before I do that, I have to get LinuxCNC back on the computer, which I can't do right now. 
https://forum.linuxcnc.org/42-deutsch/50655-linuxcnc-neuinstallation-aber-welche

**Comment by M-u-e-c-k-e** [comment]
Hello JT, 

please excuse my question. 
I now have Debian 12 with LinuxCNC. 

I can't get the "Tool Mesa Configuration Tool II" installed :-( I can only call it via the terminal. 
What have I done. 
1) Download zip 
2) Zip endpack to: /tmp
3) Terminal: cnc@debian:/tmp/mesact-master/mesact/src$ ./mesact

The tool opens, but I can't find it in applications :-( 

I would love to have an icon on my desk again. 

Gruß Mücke 


[Edit]
please excuse my ignorance. 
I found it in your documentation how to install it.

Thank you for your work and the tool.
