### ISSUE TITLE
error compiling with E-stop

### ISSUE THREAD

**Issue by kang2k10** [jethornton/mesact#4]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/libmesact/buildconfig.py", line 65, in build
    buildio.build(parent)
  File "/usr/lib/python3/dist-packages/libmesact/buildio.py", line 181, in build
    contents.append(f'net remote-estop estop-latch.0.fault-in <= hm2_7i92.0.{card}.0.{port}.input-{i:02}{invert}\n')
UnboundLocalError: local variable 'card' referenced before assignment

mesa 7i97

**Comment by jethornton** [comment]
This is not an issue with the 7i97 configuration tool, the error is for the Mesa Configuration Tool.
Please report the error in the correct tool.
https://github.com/jethornton/mesact

**Comment by kang2k10** [comment]
this issue in the measCT version 0.4.5
i update to 0.5.0 and all good
