### ISSUE TITLE
Tab reihenfolge 

### ISSUE THREAD

**Issue by M-u-e-c-k-e** [jethornton/mesact#40]
Hello, 

I use the keyboard a lot, so I often use the TAB key to jump to the next field. 
But unfortunately the tab order is often mixed up, so that you don't jump in order, but across. 

I started at 1: 
![grafik](https://github.com/jethornton/mesact/assets/103420027/184a9318-5a06-4d0e-a738-7df6bc28b5f6)
Greetings

**Comment by jethornton** [comment]
Setting the tab order in the QT Designer is very difficult when you have more than 1,650 tabs to set and you must set them all at the same time. One mistake or add or change something and all the work to set the tabs is lost. It is very frustrating for me. I too like to use the tab key to navigate. If you find a solution let me know.

JT

**Comment by M-u-e-c-k-e** [comment]
Oh yes, I can understand that. 

Unfortunately, I'm not familiar with this type of programming. 
I'm afraid I can't help. 

In HTML there is the "tabindex" where each page starts with a new 1,000 ;-) 

However, I am not familiar with programming and cannot provide qualified help. Sorry.

**Comment by jethornton** [comment]
Editing the tab order does not require any programming knowledge. After cloning the mesact repo you simply open up mesact.ui in the QT Designer and select Edit > Edit Tab Order. The you click on each green box with the tab order number and it turns blue. After you set all the tab orders you must save the file. Then you do a Pull Request. QT Designer can be installed with sudo apt install qttools5-dev-tools
![Screenshot at 2023-11-14 09-01-16](https://github.com/jethornton/mesact/assets/5452476/40a7e93e-f5b9-4c7d-a416-6934635ccb5b)
JT

**Comment by M-u-e-c-k-e** [comment]
That sounds like a good plan. 
I'll be happy to do this as soon as I get my LinuxCNC 2.9.1 running with the Mesa 7i95, as I'm always getting read errors :-(, it's taking up all my attention at the moment.

**Comment by M-u-e-c-k-e** [comment]
If I do this, will you incorporate the changes into your version? Or do I have to recreate them after every update? Or is it only changed for me after updates?

**Comment by jethornton** [comment]
If you do a Pull Request then I can incorporate the changes into master provided there are no conflicts. So before you start tell me and do a fresh pull to get the latest. I will make sure I don't change any while waiting for you. I did do some from the start yesterday. You can pick the last tab order that is in sequence and right click and select start from here.
![Screenshot at 2023-11-15 07-52-56](https://github.com/jethornton/mesact/assets/5452476/bb3a069b-bc1b-41a6-97d8-7dc27b20e1e7)

JT

**Comment by M-u-e-c-k-e** [comment]
Oh, that's good. I can't yet estimate when I'll get round to it. It'll be a while yet. I'll let you know when I can start.

**Comment by jethornton** [comment]
This has been fixed.
