### ISSUE TITLE
Missing INCREMENTS

### ISSUE THREAD

**Issue by M-u-e-c-k-e** [jethornton/mesact#42]
Hello, 

I miss the option to store the INCREMENTS. 

https://linuxcnc.org/docs/2.6/html/config/ini_config.html#sub:DISPLAY-section

z.B. in der INI 
[DISPLAY]
INCREMENTS = 1.00mm, 2.00mm, 5.00mm, 10.00mm, 20.00mm

These can be freely selected and are separated by a comma. 

gruß  Mücke

**Comment by jethornton** [comment]
Thanks
JT
