### ISSUE TITLE
Endless axis value is not accepted. 

### ISSUE THREAD

**Issue by M-u-e-c-k-e** [jethornton/mesact#43]
Hello, 

When creating an endless axis, I was unable to enter the required value (-1e99). 

Dokumentation: 
[linuxcnc.org/docs/2.7/html/config/ini-config.html](http://linuxcnc.org/docs/2.7/html/config/ini-config.html)

Zitat: 
MIN_LIMIT = -1000 - The minimum limit for axis motion, in machine units. When this limit is reached, the controller aborts axis motion. The axis must be homed before MIN_LIMIT is in force. **For a rotary axis with unlimited rotation having no MIN_LIMIT for that axis in the [AXIS_n] section then the value -1e99 is used.** 

![grafik](https://github.com/jethornton/mesact/assets/103420027/81aab302-2c6d-4da7-9fb0-f3998be5fcb6)

Gruß Mücke

**Comment by jethornton** [comment]
This was fixed yesterday
https://github.com/jethornton/mesact/commit/ab9589

JT

**Comment by M-u-e-c-k-e** [comment]
Then I was too slow. 

How can I transfer the new version?

**Comment by jethornton** [comment]
If you downloaded a deb file and installed that simply from the mesact download menu download the deb and reinstall. I don't create a new version for every small bug fix. I do update the build date.

JT
