### ISSUE TITLE
Homing not correctly assigned

### ISSUE THREAD

**Issue by M-u-e-c-k-e** [jethornton/mesact#44]
Hello everyone, 

I have just put Joint (0, 1, 2 and 3) into operation. 

When setting up Homing Joint 3, I noticed that my values were written in Joint 0 Homimg.  

I guess a few variables got mixed up ;-) 

![grafik](https://github.com/jethornton/mesact/assets/103420027/fea84306-c9be-4a11-9047-57e59fd02ed2)

Gruß Mücke

**Comment by jethornton** [comment]
Attach your ini file, I'm unable to reproduce that.

JT

**Comment by M-u-e-c-k-e** [comment]
INI does not take the portal therefore renamed to TXT. 

[7i95_it.txt](https://github.com/jethornton/mesact/files/13367275/7i95_it.txt)

**Comment by jethornton** [comment]
I am getting home search velocities that are mixed up, the variables are named correctly so I have a bug in the code.

JT

**Comment by M-u-e-c-k-e** [comment]
OK, you can reproduce it, that's already a step towards finding a solution. 

Then I don't have to do anything for the time being.

**Comment by jethornton** [comment]
Let me know if the last commit fixes this issue for you.

JT

**Comment by M-u-e-c-k-e** [comment]
**Test results in error! 

How did I test.

1) Test values. (up to joint 4) (7i95) 
Build values together Joint + number 
 Example: 
  Joint 0
  HOME = 00 (joint 0 + number 0) 
  HOME_OFFSET = 01 (joint 0 + number) 
  .... 
That was OK! 

2) Test True or False
  HOME_IGNORE_LIMITS
  HOME_USE_INDEX
  HOME_IS_SHARED

Joint 0
Set and update are OK

Joint 1, 2, 3, 4
Set and update not OK. 
**True or False is always transferred to Joint 0! not in Joint 1, 2, 3 or 4**

I hope you understand what I did and what didn't work. 


Greetings Mücke

**Comment by jethornton** [comment]
YIPPEE I found the tiny little bug in my code

JT

**Comment by M-u-e-c-k-e** [comment]
The little things make all the difference ;-). 
I'll test it later. 

THANK YOU ! 
Mücke

**Comment by M-u-e-c-k-e** [comment]
Everything is getting mixed up for me now. Joint 3 & 4 should not get any homing. 
If I do this, homing is no longer correct! all homing values are mixed up.  

Now nothing is right in homing :-( 

[7i95_it_INI.txt](https://github.com/jethornton/mesact/files/13401798/7i95_it_INI.txt)

**Comment by jethornton** [comment]
If you had something in a joint homing then remove it from the tool it does not remove it from the ini?

JT

**Comment by jethornton** [comment]
I found a mistake in testing for a blank home entry in the tool which would cause this error.
