### ISSUE TITLE
IO pins not updated correctly 

### ISSUE THREAD

**Issue by M-u-e-c-k-e** [jethornton/mesact#50]
When I open this configuration (ZIP), I have different IO pins in MesaCT than in the io.hal. 
When I say Save in MesaCT, the wrong pins are also in the io.hal. 

I don't understand where the wrong pins come from. 
![grafik](https://github.com/jethornton/mesact/assets/103420027/ea595b74-86fc-490f-b9f3-c3a37475f5a3)

[7i95_it.zip](https://github.com/jethornton/mesact/files/13401827/7i95_it.zip)

Greetings Mücke

**Comment by jethornton** [comment]
I'm not seeing any differences can you be more specific in what is different?

JT
