### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by hpeyerl** [jethornton/mesact#54]
Fumbling my way through my 7i96s configuration having just received the card and not knowing what I'm doing.  I got this error after working through it and passing Check-Config; this happened when I tried to write the config.

```
Mesact Version: 2.0.7 Build Date: 11/19/2023
  File "libmesact/buildconfig.py", line 53, in build
    parent.updateini.update(parent, iniFile)
  File "libmesact/updateini.py", line 104, in update
    last_end = self.sections[last_key][1] + 1
                            ^^^^^^^^
UnboundLocalError
cannot access local variable 'last_key' where it is not associated with a value
Please file an issue at
https://github.com/jethornton/mesact/issues
```

**Comment by jethornton** [comment]
Can you tell me what you changed when you tried to update the ini file?

Attach the ini file if you can.

JT

**Comment by hpeyerl** [comment]
Sadly, I've since overwritten that .ini file with pncconf.  I just got my 7i96s and have been trying to figure it out.  I used mesactl to flash the firmware onto my board and I don't really know what steps I took.  I did run through the whole setup of axis and such, and gui selection, etc.

Sorry.
