### ISSUE TITLE
E-Stop questions 

### ISSUE THREAD

**Issue by M-u-e-c-k-e** [jethornton/mesact#55]
Hello,

I have noticed that the machine always remains in E-Stop mode after removing the E-Stop code. 

Could you please explain why this is the case? 

At the moment I am not able to take the machine out of E-Stop mode via the graphical user interface (GUI) (without the E-Stop code in the HAL) 

Greetings Mücke 

[demo2023_ini.txt](https://github.com/jethornton/mesact/files/13691759/demo2023_ini.txt)
[main_hal.txt](https://github.com/jethornton/mesact/files/13691761/main_hal.txt)
[io_hal.txt](https://github.com/jethornton/mesact/files/13691764/io_hal.txt)

**Comment by jethornton** [comment]
It's an internal function of LinuxCNC that must be connected by some means in hal.
https://github.com/jethornton/mesact/blob/master/mesact/src/libmesact/buildhal.py#L470
