### ISSUE TITLE
reading existing INI files

### ISSUE THREAD

**Issue by bhowiebkr** [jethornton/mesact#55]
Hey does your tool read from existing INI files? If not what needs to be changed in order for that to work. BTW I have a similar tool https://github.com/bhowiebkr/LinuxCNC-Config-Editor but is more of a reader with somewhat integrated help for parameters, etc.

**Comment by jethornton** [comment]
The mesact tool only reads files created by it. If by existing ini files you mean files created by the stepconf wizard, pncconf or by hand, no.

JT

**Comment by jethornton** [comment]
I have updated the Mesa Configuration tool to try and open any ini file.
