### ISSUE TITLE
attribute error

### ISSUE THREAD

**Issue by Walkahz** [jethornton/mesact#57]
following error code comes up when trying to build config

Mesact Version: 2.0.6 Build Date: 11/15/2023
  File "../../usr/lib/python3/dist-packages/libmesact/buildconfig.py", line 57, in build
    buildhal.build(parent)
  File "../../usr/lib/python3/dist-packages/libmesact/buildhal.py", line 492, in build
    for option in parent.ladderOptionsList:
                  ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError
'MainWindow' object has no attribute 'ladderOptionsList'
Please file an issue at
https://github.com/jethornton/mesact/issues

**Comment by jethornton** [comment]
Thank you for reporting this error.
