### ISSUE TITLE
When creating a build with 7i97 selected, and no daughterboard selected, I get an error

### ISSUE THREAD

**Issue by The-Gingineer** [jethornton/mesact#59]
I get the following error: 
```

Mesact Version: 2.0.8 Build Date: 12/27/2023
  File "libmesact/buildconfig.py", line 57, in build
    buildhal.build(parent)
  File "libmesact/buildhal.py", line 197, in build
    halContents.append(f'net joint.{i}.output => hm2_[MESA](BOARD).0.{daughter_card}.0.{port}.analogout{i}\n')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError
cannot access local variable 'port' where it is not associated with a value
Please file an issue at
https://github.com/jethornton/mesact/issues
```
It appears MesaCT doesn't want to configure an axis to the 7i97 analog out.

**Comment by jethornton** [comment]
I've fixed that error but there are still some bugs with the 7i97 because it's so different. I'll try and sort that out. There is a sample 7i97 config on the Mesa site and I'm using that to fix my tool.

JT

**Comment by jethornton** [comment]
I have a 7i97T now and I'm working on making a working configuration for it

**Comment by jethornton** [comment]
Mesa CT will build a config that does not error out with a 7i97T. I do not have any hardware connected to my 7i97T so I can't test further. If everything works for you please close this issue.
