### ISSUE TITLE
Mesact fails to buld config

### ISSUE THREAD

**Issue by spumco1234** [jethornton/mesact#67]
Just updated to 2.1.0 and tried to build a test config.

Not sure if I'm missing something in the settings (_was a 'bare-bones' config_), but I got the attached error screen when I selected Build Config.

Check Config passed OK.

Was able to flash 7i96s firmware OK, using custom firmware file from PCW.

Let me know what else you need to troubleshoot.
![Screenshot_2024-01-14_04-58-38](https://github.com/jethornton/mesact/assets/103517737/245fa456-cd7c-4e24-ae17-887340ca365b)

**Comment by jethornton** [comment]
Download and reinstall 2.1, that bug was fixed a couple of days ago
https://github.com/jethornton/mesact/commit/608afbe9fa852752cf576932e8be320f7a8f89c1

**Comment by spumco1234** [comment]
Downloaded and reinstalled, and got a similar - but not the same - error.
![Screenshot_2024-01-15_02-17-56](https://github.com/jethornton/mesact/assets/103517737/00075c81-dcfe-4014-878d-6956ce5e7c00)

**Comment by jethornton** [comment]
I'm in the middle of reworking the buildio.py and should have that fixed and as soon as I'm done I'll push.
