### ISSUE TITLE
Disabling spindle encoder is not reflected ini ini file

### ISSUE THREAD

**Issue by Vorms** [jethornton/mesact#69]
**Version and Build Date**
Version = 1.1.2
Build Date =11/12/2022

With an 7I97 card

**To Reproduce**
1) Load a config with spindle encoder enabled
2) Set the feedback to none
3) Buid config
4) Check ini file or reload config

**Config File**
[SPINDLE_0]
SPINDLE_TYPE = analog
SPINDLE_PWM_TYPE = 0
PWM_FREQUENCY = 5000
MAX_RPM = 5000
MIN_RPM = 5
FEEDBACK = encoder

**Operating System**
 OS =  Debian 10

**Comment by jethornton** [comment]
Thank you for the feedback, this has been fixed.
