### ISSUE TITLE
Spindle Feedback / Settings not remembered or generated

### ISSUE THREAD

**Issue by kiki64** [jethornton/mesact#7]
I am using a Mesa 7i96S.

Under the Spindle tab, 
Spindle - Feedback, Spindle Settings - Max Acceleration, and PID Settings - Encoder Scale don't seem to remember their settings when reloading the ini file.  The other settings appear to work.  I didn't test StepGen on that tab.

In the hal file none of the encoder settings are added.  I as able to get around this by coping the settings created with pncconf for the 7i96 and changing them.
```
# ---Encoder feedback signals/setup---

setp    hm2_7i96s.0.encoder.00.counter-mode 0
setp    hm2_7i96s.0.encoder.00.filter 1
setp    hm2_7i96s.0.encoder.00.index-invert 0
setp    hm2_7i96s.0.encoder.00.index-mask 0
setp    hm2_7i96s.0.encoder.00.index-mask-invert 0
setp    hm2_7i96s.0.encoder.00.scale 4000

net spindle-revs             <=   hm2_7i96s.0.encoder.00.position
net spindle-vel-fb-rps       <=   hm2_7i96s.0.encoder.00.velocity
net spindle-vel-fb-rpm       <=   hm2_7i96s.0.encoder.00.velocity-rpm
net spindle-index-enable     <=>  hm2_7i96s.0.encoder.00.index-enable
```

**Comment by jethornton** [comment]
Thanks for the feedback, I'll add that to the spindle section which is still somewhat under construction.
