### ISSUE TITLE
Name Error...

### ISSUE THREAD

**Issue by Jackass-jpg** [jethornton/mesact#71]
JET:
Thanks for your work on this, fellow School of Hard Knocks grad...

Likely upstream of this as my Debian install was not without issues.
Also I am chasing down a potential hardware issue in the 7i76e board.
Fun!
In other words, don't spend too much time on this, might very well be on my end...

Got this when using Mesa Config Tool V 2.101 Build 1/15/24
 and clicking on "Verify Board":
Under "Mesa Setup", with the following selections:
**BOARD:** 7i76E
**IP ADDRESS:** 192.168.1.121 (and pings as such)
**Click on:** "Verify Board" then:
______________________________
line 124, in verify_board
if not board:
         ^^^^^

NameError
name 'board' is not defined
Please file and issue at
(well, this site.)

**Comment by jethornton** [comment]
Thanks for the report.
