### ISSUE TITLE
Support for 7i92+7i76+7i85s

### ISSUE THREAD

**Issue by Levente71** [jethornton/mesact#8]
Mesact supported configuration for **7i92** + **7i76** in P2 and **7i85s** in P1 ?
I not found firmware this. (pin and bit files)

**Comment by jethornton** [comment]
I only see 7i92_7i77_7i85sd.bit, so Peter would have to generate one.

JT

**Comment by Levente71** [comment]
Thank you. I'm waithing for Peter. Because I build cnc mill and use 7i92+7i76+7i85s card combination. But I can not to upload firmware.

Thx,
Levi
