### ISSUE TITLE
mesact don't take car of the ip address of the mesa card

### ISSUE THREAD

**Issue by Vorms** [jethornton/mesact#81]
**Version and Build Date**
Version = 1.2.1
Build Date =

**Describe the bug**
I changed the ip of the card.
I put the new adress in the configuration setup ip address
I build the config 
The ip address of the [HM2] is the old address.

**Comment by jethornton** [comment]
I can not reproduce this behavior. A step by step on how you changed the ip address would help.

**Comment by jethornton** [comment]
I tested several different IP addresses and the ini file is correct after building new or updating a configuration.
