### ISSUE TITLE
7i95T Spindle Tab Unavailable 

### ISSUE THREAD

**Issue by sbvr4** [jethornton/mesact#82]
Hi,

I'm attempting to configure my 7i95T for use with the PWM firmware and the spindle tab is grayed out. This seems to do the same for the couple different 7i95T firmwares I've tried. I did notice that if I open an existing 7i95T config and switch the board selection to 7i96S and then back to 7i95T the spindle tab is then available and I can save. This isn't very efficient though, since changing the board deletes all of the existing perimeters and I have to renter everything. I'm not sure if I am doing something wrong, or it's a bug. Thank you creating and maintaining this awesome software.

Sean

**Comment by jethornton** [comment]
The 7i95T doesn't have a spindle PWM output nomally AFAIK. Well there is a firmware for 7i95t_1pwmd.bin... it looks like the PWM  replaces stepgen 5... that could be quite complicated to program into the tool but I'll look into it. At some point in every configuration you need to edit the files manually even though I try to have as much as possible in the tool.

JT
