### ISSUE TITLE
Errors after new install linuxcnc 2.9.2

### ISSUE THREAD

**Issue by matcador** [jethornton/mesact#83]
I get this error when i start mesact . With mesact 2.1.1 i get the same error.
![Capture d’écran_2024-02-03_15-56-10](https://github.com/jethornton/mesact/assets/158754748/e2d7d41c-a0e7-4eb4-b1cd-ae682fefb119)

**Comment by jethornton** [comment]
What does `apt-cache policy linuxcnc-uspace` return?
How did you install LinuxCNC?

**Comment by jethornton** [comment]
I'm pretty sure I made the test bullet proof and when I push this will get closed. I still want to know what the output of the above command is on your PC.

**Comment by matcador** [comment]
HI, attached is what i get from apt-cache.envoyé : 4 février 2024 à 13:38de : jethornton ***@***.***>à : jethornton/mesact ***@***.***>cc : matcador ***@***.***>, Author ***@***.***>objet : Re: [jethornton/mesact] Errors after new install linuxcnc 2.9.2 (Issue #83) What does apt-cache policy linuxcnc-uspace return—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
