### ISSUE TITLE
module not found error "distro" 

### ISSUE THREAD

**Issue by VonSzarvas** [jethornton/mesact#93]
Hi!

Fresh Bookworm debian 12 install
Downloaded and installed mesact2.1.3.amd64

running mesact from gui doesn't appear to do anything
so tried from the command line, it won't run, and returns the module not found error (image attached).

Is there an issue with me or the build ? :)   
Either way, figured you should know.  
All the best.

![viber_image_2024-04-18_17-54-10-257](https://github.com/jethornton/mesact/assets/11635798/66290916-db2a-4b93-a7ef-97b1b806a0b8)

**Comment by VonSzarvas** [comment]
correction... this was a fresh "linuxcnc-2.9.2" install, downloaded today.

also...  just tried mesact-2.1.2 -  that installs & appears to run ok on this pc, so just something on 2.1.3 not quite working.

**Comment by jethornton** [comment]
Did you download LinuxCNC from the downloads page http://linuxcnc.org/downloads/?

The python3-distro "should" be standard, can you check to see if it's installed? If not I'll add that as a dependency.

Edit: I added an OS check to 2.1.3 as a user tried to run it on a non Debian OS.

JT

**Comment by VonSzarvas** [comment]
> Did you download LinuxCNC from the downloads page http://linuxcnc.org/downloads/?

Correct, yes.

And confirmed, adding python3-distro resolved the issue.
THANK YOU so much !!!
