### ISSUE TITLE
mesact/buildini.py [HAL] missing io.hal

### ISSUE THREAD

**Issue by seiptp** [jethornton/mesact#95]
https://github.com/jethornton/mesact/releases/tag/1.2.3

When a new project is created and a the <project>.ini file is generated, the inclusion of the io.hal under the [HAL] section is missing.
Expection:
```
[HAL]
HALFILE = <project>.hal
HALFILE = io.hal
HALFILE = custom.hal
```

To reproduce create new project and check <project>.ini

OS =  Debian 10

**Comment by seiptp** [comment]
https://github.com/jethornton/mesact/blob/9b05831083ab56203294c4be5f001788cc49e597/mesact/src/libmesact/buildini.py#L134

**Comment by jethornton** [comment]
Fixed
