### ISSUE TITLE
Library problem

### ISSUE THREAD

**Issue by zz912** [jethornton/mesact#97]
If I installed MesaCT, it has problem with library:
 
![mesact-lib-problem](https://user-images.githubusercontent.com/96618597/223624299-7e877cf0-0361-4623-99a8-3134d5a06d4a.png)

I solved it for myself easy. I copied library from Github to folder and it works.

**Comment by jethornton** [comment]
When you have an issue first select Help > Check for Updates to see if you have the latest version. The current version is 1.2.3

**Comment by zz912** [comment]
The problem was that when the 1.2.2 version wouldn't start, I couldn't go "Help > Check for Updates" to see that there was a 1.2.3 version.

**Comment by jethornton** [comment]
I did forget to upload the latest html page...
https://gnipsel.com/linuxcnc/mesact/install.html

**Comment by zz912** [comment]
There is still problem:
/1.2.2/mesact_1.2.3_amd64.deb - wrong
/1.2.3/mesact_1.2.3_amd64.deb - better
