### ISSUE TITLE
PC+NIC test - maybe wrong? 

### ISSUE THREAD

**Issue by zz912** [jethornton/mesact#98]
Hello,

can I ask you for your opinion?
https://forum.linuxcnc.org/27-driver-boards/48369-optiplex-755?start=10#266214

I like your tests, but I'm having trouble imagining what they say.

Zdeněk

**Comment by jethornton** [comment]
Sorry, the calculation was wrong and has been fixed.

**Comment by zz912** [comment]
Thank you.

**Comment by zz912** [comment]
It is weird fix.
![Mesact-wrong_fix](https://user-images.githubusercontent.com/96618597/224362643-a0dc6f1d-4c57-449a-888b-079e7a7f36f9.png)

**Comment by jethornton** [comment]
At the moment I can't run LinuxCNC on this dev pc because of the opengl issue with debian...

**Comment by jethornton** [comment]
So far I'm unable to figure out the formula even after asking Peter a few times for help...

**Comment by zz912** [comment]
Thank you for info.
