### ISSUE TITLE
Build Config error on 7i95t

### ISSUE THREAD

**Issue by kworm83** [jethornton/mesact#98]
I'm getting the attached error when attempting to build config.  The check config says all is ok.  I downloaded the latest .deb just to make sure and get the same results.  Looks like this reference to "board" was added in commit 5561efc a few days ago.
![mesact error](https://github.com/jethornton/mesact/assets/21957311/c3252c34-92a0-4381-9b4f-1e035cbf0dda)

**Comment by jethornton** [comment]
Thanks for the report.
